### PR TITLE
fix the typo.

### PR DESCRIPTION
**Pull request by Haroenv**
remeber --> remember

better pull request @pixelass ?

### CODE REVIEW

**Comment by pixelass** [comment]
LOL.. thx. it was a joke, but yeah.. better.

**Comment by Haroenv** [comment]
You wrote `remebmer` now @pixelass

**Comment by pixelass** [comment]
duuuh. Well now I added you to the repo so you can do in-org PRs 

and I fixed the typo ;)

**Comment by Haroenv** [comment]
You made it worse :anguished:

**Comment by Haroenv** [comment]
Ah it's fixed now!

**Comment by pixelass** [comment]
please take discussions into the gitter channel ;)

**Pull request closed without merging**
